title: Isalos Analytics Platform Docs
description: The Documentation of Isalos Analytics Platform powered by Just the docs
theme: just-the-docs

baseurl: "/docs"
url: https://www.docs.isalos.novamechanics.com/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

example: ok

color_scheme: light

exclude:
  - "node_modules"
  - ".git"
  - "vendor"
  - ".bundle"
  - "Gemfile.lock"
  - "README.md"
  - ".github"
